// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKvU21_yFUYdsWbrM_0Sj_dsx6NbJw1tI',
    appId: '1:451212338777:web:6d465205d392440a5eb348',
    messagingSenderId: '451212338777',
    projectId: 'test-login-e28f1',
    authDomain: 'test-login-e28f1.firebaseapp.com',
    storageBucket: 'test-login-e28f1.firebasestorage.app',
    measurementId: 'G-K5PH3RKS8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9P7u0rLfLTn1tp9QTr1ZZk9Q0n0BVas',
    appId: '1:451212338777:android:125ee269fff24fa25eb348',
    messagingSenderId: '451212338777',
    projectId: 'test-login-e28f1',
    storageBucket: 'test-login-e28f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLA1iFHWhhA4nXsuagxwMh7_nB9-S6VnM',
    appId: '1:451212338777:ios:618fa6d7fa68c5f15eb348',
    messagingSenderId: '451212338777',
    projectId: 'test-login-e28f1',
    storageBucket: 'test-login-e28f1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLA1iFHWhhA4nXsuagxwMh7_nB9-S6VnM',
    appId: '1:451212338777:ios:618fa6d7fa68c5f15eb348',
    messagingSenderId: '451212338777',
    projectId: 'test-login-e28f1',
    storageBucket: 'test-login-e28f1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKvU21_yFUYdsWbrM_0Sj_dsx6NbJw1tI',
    appId: '1:451212338777:web:5adbc8ab09cbd6905eb348',
    messagingSenderId: '451212338777',
    projectId: 'test-login-e28f1',
    authDomain: 'test-login-e28f1.firebaseapp.com',
    storageBucket: 'test-login-e28f1.firebasestorage.app',
    measurementId: 'G-YL5TVY4FBW',
  );

}